'use strict';
let data=null, currentPage='overview', selectedRun='', paused=false, busy=false;
const $=id=>document.getElementById(id), number=x=>Number(x||0).toLocaleString('zh-CN');
const names={completed:'已完成',valid:'校验通过',invalid:'校验失败',pending:'待开始',planned:'未开始',in_progress:'进行中',running:'运行中',searching:'候选搜索',evaluating_holdout:'留出评测',writing:'生成报告',paused:'已暂停',failed:'失败',interrupted:'已中断',budget_exhausted:'预算不足',requesting:'模型请求中',awaiting_supervisor:'待监督审核',supervisor_reviewed:'已监督审核',settled:'已结算',unknown:'用量未知',active:'进行中',unavailable:'未校验',initialized:'已初始化',retain:'保留',reject:'淘汰',partially_accepted_as_design_proposals:'部分采纳，仅作为设计建议',not_started:'尚未开始',protocol_design:'实验协议设计中'};
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined&&text!==null)node.textContent=String(text);if(cls)node.className=cls;return node}
Object.assign(names,{accepted:'已验收',awaiting_review:'待评审 / 审核',stale:'证据已失效',changes_requested:'需补充修改',rejected:'已拒绝',terminated:'已终止',ready:'可继续执行',completed_with_errors:'完成但有失败任务'});
Object.assign(names,{waiting_for_gateway:'等待模型网关',needs_attention:'异常待处理',deadline_exceeded:'达到时间上限',stopped:'按审查或停止条件结束',evaluated:'已完成实验'});
Object.assign(names,{search_plan:'规划文献检索',search:'检索与留存文献',topics:'提出课题',topic_review:'独立选题审查',select:'冻结选题',baseline:'基线实验',propose:'提出实验',design_review:'实验设计审查',development:'开发集实验',next:'决定后续实验',freeze:'冻结正式协议',evaluation:'正式评价',interpretation:'结果解释审查',write:'撰写论文',paper_review:'论文审查',export:'导出材料',done:'流程结束',infeasible:'缺少执行条件',pending_review:'等待机器审查',approved:'机器审查通过'});
function renderProjects(){
 const root=clear('project-progress');
 for(const p of data.projects||[]){
  const card=panel(p.id+(p.open_topic?' · 开放选题自主研究':p.autonomous?' · 自主研究':' · 版本 '+p.revision));
  card.querySelector('.section-head').append(status(p.status));
  card.append(el('p',p.question),el('p',`已结算/保留预留 ${number(p.model_tokens_charged_or_reserved)} / ${number(p.model_token_limit)} Token · 正式评价${p.holdout_exposed?'已开始，不能回到搜索':'尚未开始'}`,'muted'));
  const wrap=el('div',undefined,'table-wrap');
  if(p.autonomous){
   card.append(el('p',`当前阶段：${names[p.phase]||p.phase} · 实验候选 ${p.attempt}/${p.max_candidates} · ${p.fixture_only?'合成验收，真实模型调用为零':'真实研究，模型调用意图 '+p.model_calls}`));
   if(p.open_topic){
    card.append(el('p',`选题轮次：${Math.min(p.topic_round+1,p.max_topic_rounds)}/${p.max_topic_rounds} · 通过 ${p.topic_counts.approved} · 条件不足 ${p.topic_counts.infeasible} · 被拒绝 ${p.topic_counts.rejected}`));
    card.append(table(['研究问题','实验能力','优先级','状态','缺口'],p.topics.map(t=>[t.question,t.domain,t.priority,status(t.status),t.issues.join('；')||'—'])));
    if(p.selected_topic)card.append(el('p','已冻结课题：'+p.selected_topic.question));
    for(const [alias,limit] of Object.entries(p.model_budgets))card.append(el('p',`${alias}: ${number(p.model_usage[alias])} / ${number(limit)} Token，包含选题、审查和写作`,'muted'));
   }
   if(p.progress?.total)card.append(progress(p.progress.completed,p.progress.total),el('p',`${p.progress.split}: ${p.progress.completed}/${p.progress.total}`,'muted'));
   wrap.append(table(['候选','状态','开发指标','优于当前最佳'],p.trials.map(t=>[t.attempt,status(t.status),t.result?.score?.toFixed(4)||'—',t.improved?'是':'否'])));
   for(const r of (p.reviews||[]).slice(-3))card.append(el('p',`${r.id} · 机器审查：${r.reviews.map(x=>x.alias+': '+x.verdict).join(' / ')}`));
   if(p.last_error||p.stop_reason)card.append(el('p',p.last_error||p.stop_reason,'warning'));
   card.append(fileButtons(p.artifacts||[]),el('p','自动完成表示流程结束；机器审查不等于人工同行评审或论文录用。','muted'));
  }else{
   wrap.append(table(['阶段','状态','等待 / 依赖','尝试'],p.stages.map(s=>[s.id,status(s.status),s.blocked_by.length?'等待 '+s.blocked_by.join(', '):s.needs.join(', ')||'无',s.attempts])));
   for(const d of (p.decisions||[]).slice(-4))card.append(el('p',`${d.stage} · ${d.action} · ${d.actor}：${d.reason}`));
   card.append(el('p','阶段验收表示流程决策已记录，不等于科学结论成立。','muted'));
  }
  card.append(wrap);root.append(card);
 }
 if(!(data.projects||[]).length)empty(root,'尚未创建研究项目。');
}
function clear(id){const node=typeof id==='string'?$(id):id;node.replaceChildren();return node}
function status(value){const tone=['completed','valid','settled','supervisor_reviewed'].includes(value)?'green':['failed','invalid','budget_exhausted'].includes(value)?'red':['unknown','awaiting_supervisor','interrupted'].includes(value)?'amber':['running','searching','in_progress','requesting','evaluating_holdout','writing','active'].includes(value)?'blue':'';return el('span',names[value]||value||'未知','pill '+tone)}
function date(value){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.valueOf())?value:d.toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})}
function panel(title){const node=el('article',undefined,'panel'),head=el('div',undefined,'section-head');head.append(el('h2',title));node.append(head);return node}
function empty(node,text='暂无记录'){node.append(el('div',text,'empty'))}
function progress(done,total){const bar=el('div',undefined,'progress'),fill=el('span');fill.style.width=(total?Math.min(100,done/total*100):0)+'%';bar.append(fill);return bar}
function table(headers,rows){const t=el('table'),head=el('thead'),tr=el('tr');headers.forEach(x=>tr.append(el('th',x)));head.append(tr);t.append(head);const body=el('tbody');for(const row of rows){const line=el('tr');for(const value of row){const cell=el('td');cell.append(value instanceof Node?value:document.createTextNode(value??'—'));line.append(cell)}body.append(line)}t.append(body);return t}
function fileButtons(files){const node=el('div',undefined,'artifact-buttons');for(const file of files||[]){const button=el('button',file.name,'artifact-button');button.onclick=()=>preview(file);node.append(button)}return node}
async function preview(file){$('preview-title').textContent=file.path;$('preview-content').textContent='正在读取…';$('preview-meta').textContent='只读预览';if(!$('preview').open)$('preview').showModal();try{const r=await fetch('/api/artifact?path='+encodeURIComponent(file.path),{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('文件未开放或读取失败');const v=await r.json();$('preview-content').textContent=v.text;$('preview-meta').textContent=v.truncated?'文件较长，仅显示前 250,000 字符':'只读原文 · 不执行文档中的代码或指令'}catch(e){$('preview-content').textContent=e.message}}
function go(page){currentPage=page;document.querySelectorAll('.page').forEach(x=>x.hidden=x.id!=='page-'+page);document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('page-title').textContent={overview:'科研总览',experiments:'实验与结果',tasks:'模型任务与监督',models:'Token 与资源',evidence:'证据与文档',events:'活动日志'}[page];if(data)renderPage();}
document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>go(x.dataset.page));document.querySelectorAll('[data-jump]').forEach(x=>x.onclick=()=>go(x.dataset.jump));
$('close-preview').onclick=()=>$('preview').close();$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'恢复刷新':'暂停刷新';$('connection').textContent=paused?'刷新已暂停':'正在连接…';if(!paused)refresh()};$('refresh').onclick=()=>refresh(true);
$('run-select').onchange=()=>{selectedRun=$('run-select').value;renderRun()};$('task-filter').onchange=renderTasks;$('model-filter').onchange=renderModels;$('artifact-search').oninput=renderArtifacts;$('event-search').oninput=renderEvents;
function renderOverview(){const v4=clear('v4-progress'),v=data.research_v4||{};v4.append(el('p',v.summary||'尚未登记第四版证据'));for(const row of v.decisions||[])v4.append(el('p',`${row.candidate} → ${row.decision}：${row.reason}`));v4.append(el('p',`主张证据 ${v.claims_verified||0}/${v.claims_total||0} · 审查问题关闭 ${v.issues_closed||0}/${v.issues_total||0}`,'muted'));const roadmap=data.roadmap||{};$('research-title').textContent=roadmap.title||'尚未登记研究方向';$('research-question').textContent=roadmap.question||'';$('research-note').textContent=roadmap.note||'没有研究阶段记录';document.querySelector('.hero>.pill').textContent=names[roadmap.status]||roadmap.status||'未登记';
const stats=clear('stats');for(const [label,value,note] of [['已完成实验任务',data.totals.completed_jobs,'包含历史工程示例'],['记录为运行中',data.totals.active,'状态记录，不是进程心跳'],['待监督审核',data.totals.pending_reviews,'模型建议须验收'],['已监督审核',data.totals.reviewed_tasks,'保留原始意见和取舍']]){const s=el('div',undefined,'stat');s.append(el('div',label,'label'),el('div',number(value),'number'),el('div',note,'muted'));stats.append(s)}
const stages=clear('roadmap');(roadmap.stages||[]).forEach((s,i)=>{const node=el('div',undefined,'stage '+s.status);node.append(el('div',String(i+1).padStart(2,'0'),'stage-index'),el('h3',s.label),status(s.status),el('p',s.detail));stages.append(node)});$('next-action').textContent='下一步 · '+(roadmap.next_action||'尚未登记');
const runs=clear('overview-runs');for(const r of data.runs.slice(0,3)){const node=el('div',undefined,'run-row'),head=el('div',undefined,'row-top'),btn=el('button',r.id,'text-button');btn.onclick=()=>{selectedRun=r.id;go('experiments')};head.append(btn,status(r.status));node.append(head,progress(r.completed_jobs,r.total_jobs),el('div',`${r.completed_jobs} / ${r.total_jobs} 已创建任务完成 · ${r.attempts} 次尝试`,'muted'));runs.append(node)}if(!data.runs.length)empty(runs);
const alerts=clear('alerts');$('alert-count').textContent=data.alerts.length+' 项';for(const a of data.alerts){const node=el('div',undefined,'alert');node.append(el('strong',a.source),el('div',a.message));alerts.append(node)}if(!data.alerts.length)empty(alerts,'当前没有异常或待审核提醒');renderTimeline(clear('overview-events'),data.events.slice(0,5));}
function renderRun(){const select=$('run-select');const ids=data.runs.map(x=>x.id).join('|');if(select.dataset.ids!==ids){select.replaceChildren();for(const r of data.runs){const o=el('option',r.id);o.value=r.id;select.append(o)}select.dataset.ids=ids}if(!data.runs.some(x=>x.id===selectedRun))selectedRun=data.runs.find(x=>x.kind==='campaign')?.id||data.runs[0]?.id||'';select.value=selectedRun;const root=clear('run-detail'),r=data.runs.find(x=>x.id===selectedRun);if(!r){empty(root);return}
const top=panel(r.title);top.querySelector('.section-head').append(status(r.status));top.append(el('p',r.question,'muted'));const metrics=el('div',undefined,'mini-grid');for(const [label,value] of [['已创建任务',`${r.completed_jobs} / ${r.total_jobs}`],['执行尝试',r.attempts],['冻结选择',r.selection.method||'固定方法表']]){const m=el('div');m.append(el('span',label,'muted'),el('strong',value));metrics.append(m)}top.append(metrics,progress(r.completed_jobs,r.total_jobs));top.append(el('p',r.kind==='campaign'?`开发试验 ${r.history.length} / 上限 ${r.planned_trials??'—'}；未创建的留出任务不纳入上述进度。`:'固定计划运行；这里显示方法 × 随机种子的完成情况。','muted'));top.append(status(r.integrity.status),el('span','  最近哈希检查 '+date(r.integrity.checked_at),'muted'));if(r.integrity.errors?.length)top.append(el('p',r.integrity.errors.join('；'),'warning'));root.append(top);
const columns=el('div',undefined,'two-col'),chart=panel(r.kind==='campaign'?'留出结果':'指标摘要'),summary=r.summary||{},methods=summary.methods||[];chart.append(el('p',`${summary.metric||r.metric||'指标'} · ${r.direction==='minimize'?'越低越好':'越高越好'} · ${r.kind==='campaign'?'冻结选择后评测':'固定配置结果'}`,'muted'));const bars=el('div',undefined,'metric-bars');const scale=summary.metric==='accuracy'?1:Math.max(1e-9,...methods.map(x=>Math.abs(x.mean)));for(const method of methods){const row=el('div',undefined,'metric-row '+(method.method===r.selection.method?'selected':'')),track=el('div',undefined,'metric-track'),fill=el('div',undefined,'metric-fill');fill.style.width=Math.min(100,Math.abs(method.mean)/scale*100)+'%';track.append(fill);row.append(el('span',method.method),track,el('span',Number(method.mean).toFixed(4),'metric-value'));bars.append(row)}chart.append(bars);if(!methods.length)empty(chart,'完整结果尚未生成');else chart.append(el('p',summary.metric==='accuracy'?'横条范围 0–1；绿色表示开发集选中的方法。':'横条表示绝对值相对长度，正负方向以数值为准。','muted'));const history=panel('开发集决策');if(r.history.length){const wrap=el('div',undefined,'table-wrap');wrap.append(table(['候选','均值','相对当前最佳增益','决定'],r.history.map(h=>[h.candidate,Number(h.score).toFixed(4),(h.improvement>=0?'+':'')+Number(h.improvement).toFixed(4),status(h.decision)])));history.append(wrap)}else empty(history,'此运行没有候选搜索记录');columns.append(chart,history);root.append(columns);
const jobs=panel('任务执行矩阵');for(const grid of r.grids){const head=el('div',undefined,'row-top');head.append(el('h3',grid.name),el('span',`${grid.completed}/${grid.total} 完成 · ${grid.attempts} 次尝试`,'muted'));jobs.append(head);const matrix=el('div',undefined,'job-grid');for(const job of grid.jobs){const dot=el('div',undefined,'job '+job.status);dot.title=`${job.id} · ${names[job.status]||job.status} · ${job.attempts} 次尝试`;dot.setAttribute('aria-label',dot.title);matrix.append(dot)}jobs.append(matrix,el('div','绿色：完成　蓝色：运行　红色：失败　灰色：待执行','job-label'))}root.append(jobs);const evidence=panel('结果与证据');evidence.append(fileButtons(r.artifacts));const seconds=r.resources.measured_subprocess_seconds??r.resources.experiment_wall_seconds_including_retries;evidence.append(el('p',`子进程实测耗时：${seconds===undefined?'尚未汇总':Number(seconds).toFixed(3)+' 秒'}。统计仅描述配置任务，不证明真实 Agent 泛化或论文创新。`,'muted'));root.append(evidence);}
function renderTasks(){const root=clear('task-cards'),filter=$('task-filter').value;const tasks=data.tasks.filter(t=>filter==='all'||(filter==='attention'&&['failed','awaiting_supervisor'].includes(t.status))||(filter==='reviewed'&&t.status==='supervisor_reviewed')||(filter==='planned'&&t.status==='planned'));for(const t of tasks){const card=panel(t.task_id);card.classList.add('task-card');card.querySelector('.section-head').append(status(t.status));card.append(el('div',t.model+' · '+t.id,'eyebrow'),el('p',t.objective,'objective'));if(t.error)card.append(el('div',t.error,'notice danger'));card.append(el('p','监督结论：'+(names[t.supervisor_decision]||t.supervisor_decision),'muted'));card.append(el('p',t.applied?'记录显示：建议已应用':'模型输出未自动应用到实验','muted'));const tail=el('div',undefined,'task-footer');tail.append(el('div',t.usage?`网关报告 ${number(t.usage.total_tokens)} Token`:'未报告此任务的完整用量','muted'),fileButtons(t.artifacts));card.append(tail);root.append(card)}if(!tasks.length)empty(root,'当前筛选下没有任务');}
function renderModels(){const root=clear('model-cards');for(const [alias,m] of Object.entries(data.usage.models)){const card=panel(m.model);card.querySelector('.section-head').append(el('span',m.blocked?'预算准入已冻结':m.active_requests?'请求进行中':m.unknown_requests?'存在未结算请求':'空闲','pill '+(m.blocked?'red':m.unknown_requests?'amber':'green')));card.append(el('div',number(m.reported_tokens),'model-number'),el('p',`已报告 Token / 总上限 ${number(m.limit)} · ${(m.reported_tokens/m.limit*100).toFixed(5)}%`,'muted'),progress(m.reported_tokens,m.limit));const grid=el('div',undefined,'model-metrics');for(const [label,value] of [['输入 / 输出',`${number(m.input_tokens)} / ${number(m.output_tokens)}`],['缓存输入 / 推理输出',`${number(m.cached_input_tokens)} / ${number(m.reasoning_output_tokens)}`],['未结算预留',number(m.held_tokens)],['剩余可准入',number(m.remaining_admissible_tokens)],['请求 / 进行中',`${m.requests} / ${m.active_requests}`],['用量未知请求',m.unknown_requests]]){const node=el('div');node.append(el('span',label,'muted'),el('strong',value));grid.append(node)}card.append(grid);root.append(card)}
const filter=$('model-filter'),aliases=Object.keys(data.usage.models),current=filter.value;if(filter.dataset.aliases!==aliases.join('|')){filter.replaceChildren(el('option','全部模型'));filter.options[0].value='all';for(const alias of aliases){const op=el('option',alias);op.value=alias;filter.append(op)}filter.value=aliases.includes(current)?current:'all';filter.dataset.aliases=aliases.join('|')}
const requests=data.usage.recent_requests.filter(r=>filter.value==='all'||r.alias===filter.value),chart=clear('token-chart'),bars=el('div',undefined,'token-bars'),max=Math.max(1,...requests.map(r=>r.usage?.total_tokens||0));for(const r of requests){const col=el('div',undefined,'token-column'),bar=el('div',undefined,'token-block '+(r.usage?'':'unknown'));if(r.usage)bar.style.height=(r.usage.total_tokens/max*80)+'%';col.title=`${r.alias} · ${r.purpose} · ${r.usage?number(r.usage.total_tokens)+' Token':'用量未知'}`;col.append(el('span',r.usage?number(r.usage.total_tokens):'?'),bar);bars.append(col)}chart.append(bars,el('p','从左到右按请求顺序排列；各柱高度相对最近请求最大值。未知用量不画成零消耗。','token-labels'));clear('request-table').append(table(['模型 / 接口','用途','状态','输入','输出','已报告总量','预留','开始时间'],[...requests].reverse().map(r=>[`${r.alias} / ${r.api_format}`,r.purpose,status(r.status),r.usage?number(r.usage.input_tokens):'—',r.usage?number(r.usage.output_tokens):'—',r.usage?number(r.usage.total_tokens):'未知',r.usage?'已结算':number(r.reserved_tokens),date(r.started_at)])));}
function renderArtifacts(){const root=clear('artifact-list'),query=$('artifact-search').value.toLowerCase();const groups=[...data.runs.map(r=>({title:r.id,artifacts:r.artifacts,integrity:r.integrity})),...data.tasks.map(t=>({title:t.id,artifacts:t.artifacts})),{title:'研究方向与协议',artifacts:data.documents}];for(const g of groups){const files=g.artifacts.filter(f=>(f.path+' '+g.title).toLowerCase().includes(query));if(!files.length)continue;const card=panel(g.title);card.classList.add('artifact-group');if(g.integrity)card.querySelector('.section-head').append(status(g.integrity.status));card.append(fileButtons(files));root.append(card)}if(!root.childElementCount)empty(root,'没有匹配的公开研究产物');}
const eventNames={run_initialized:'实验初始化',run_completed:'实验完成',job_started:'任务开始',job_finished:'任务结束',job_reused:'复用已验证任务',run_paused:'运行暂停',run_failed:'运行失败',campaign_initialized:'研究循环初始化',attempt_reserved:'预留执行预算',candidate_reviewed:'候选评估完成',selection_frozen:'冻结候选选择',campaign_completed:'研究循环完成',campaign_stopped:'研究循环停止',model_completed:'模型请求已结算',model_usage_unknown:'模型请求用量未结算',model_started:'模型请求开始',model_task_updated:'模型任务状态更新',supervisor_reviewed:'监督审核完成'};
function renderTimeline(root,events){for(const e of events){const node=el('div',undefined,'event'),body=el('div');body.append(el('strong',eventNames[e.event]||e.event),el('p',[e.owner,e.job,e.candidate,e.method,e.decision&&names[e.decision],e.status&&names[e.status],e.error].filter(Boolean).join(' · ')));node.append(el('time',date(e.time)),body);root.append(node)}if(!events.length)empty(root,'暂无匹配活动');}
function renderEvents(){const q=$('event-search').value.toLowerCase();renderTimeline(clear('event-list'),data.events.filter(e=>JSON.stringify(e).toLowerCase().includes(q)));}
function renderPage(){({overview:renderOverview,experiments:renderRun,tasks:renderTasks,models:renderModels,evidence:renderArtifacts,events:renderEvents})[currentPage]();if(currentPage==='overview')renderProjects();}
async function refresh(force=false){if(busy||(paused&&!force))return;busy=true;try{const response=await fetch('/api/research',{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('数据接口返回 '+response.status);data=await response.json();renderPage();$('fatal').hidden=true;$('connection').textContent=paused?'刷新已暂停':'● 实时连接';$('connection').style.color='';$('updated-at').textContent='更新于 '+date(data.updated_at)}catch(error){$('fatal').hidden=false;$('fatal').textContent='连接中断或记录暂不可用；保留上次数据。'+error.message;$('connection').textContent='连接中断';$('connection').style.color='var(--red)'}finally{busy=false}}
refresh();setInterval(()=>refresh(),2000);
