"""Generate an explicitly labelled draft from completed, traceable experiments."""

import csv
import io
import statistics

from .storage import read_json, write_json, write_text


def summarize(plan, rows):
    metric = plan["primary_metric"]
    by_method = {method: {} for method in plan["methods"]}
    for row in rows:
        by_method[row["method"]][row["seed"]] = row["result"]["metrics"][metric]
    for seed in plan["seeds"]:
        hashes = [row["result"].get("provenance", {}).get("dataset_sha256")
                  for row in rows if row["seed"] == seed]
        if any(hashes) and (not all(hashes) or len(set(hashes)) != 1):
            raise ValueError(f"Methods used different evaluation data for seed {seed}")
    baseline = by_method[plan["baseline"]]
    summaries = []
    for method, values in by_method.items():
        if set(values) != set(plan["seeds"]):
            raise ValueError("Incomplete experiment grid; refusing paper generation")
        deltas = [values[seed] - baseline[seed] for seed in plan["seeds"]]
        summaries.append({"method": method, "n_seeds": len(values),
                          "mean": statistics.mean(values.values()),
                          "sample_stddev": statistics.stdev(values.values()),
                          "paired_delta_mean": statistics.mean(deltas),
                          "paired_delta_stddev": statistics.stdev(deltas)})
    return {"metric": metric, "direction": plan["direction"], "baseline": plan["baseline"],
            "methods": summaries, "inference": "Descriptive only; no significance or generalization claim."}


def tex_escape(value):
    replacements = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$",
                    "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}",
                    "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
    return "".join(replacements.get(char, char) for char in str(value))


def generate_reports(root, plan, rows, state):
    summary = summarize(plan, rows)
    write_json(root / "summary.json", summary)
    stream = io.StringIO(newline="")
    writer = csv.writer(stream)
    writer.writerow(["method", "seed", plan["primary_metric"], "result_path", "sha256"])
    for row in rows:
        writer.writerow([row["method"], row["seed"], row["result"]["metrics"][plan["primary_metric"]],
                         row["result_path"], row["sha256"]])
    write_text(root / "results.csv", stream.getvalue())
    evidence = [{key: row[key] for key in ("method", "seed", "result_path", "sha256")}
                for row in rows]
    write_json(root / "evidence.json", {"runs": evidence, "references": plan["references"]})
    all_attempts = [read_json(p) for p in sorted((root / "jobs").glob("*/attempt_*/execution.json"))]
    resources = {"mode": "offline-local", "model_calls_by_orchestrator": 0,
                 "model_tokens_by_orchestrator": 0,
                 "experiment_model_usage": [row["result"]["provenance"] for row in rows],
                 "total_attempts": len(all_attempts),
                 "failed_attempts": sum(r["status"] != "completed" for r in all_attempts),
                 "experiment_wall_seconds_including_retries": sum(r.get("wall_seconds", 0) for r in all_attempts),
                 "billing_cost": None,
                 "note": "Executor model use is self-reported in provenance, not independently metered. Wall time is measured; no monetary estimate."}
    write_json(root / "resource_report.json", resources)
    table = ["| Method | Mean | Sample SD | Paired delta vs baseline |",
             "|---|---:|---:|---:|"]
    for item in summary["methods"]:
        table.append(f"| {item['method']} | {item['mean']:.6f} | {item['sample_stddev']:.6f} | {item['paired_delta_mean']:+.6f} |")
    findings = []
    for item in summary["methods"]:
        if item["method"] == plan["baseline"]:
            continue
        delta = item["paired_delta_mean"]
        improvement = delta if plan["direction"] == "maximize" else -delta
        outcome = "improved" if improvement > 0 else "worsened" if improvement < 0 else "matched"
        findings.append(f"On this configured evaluation, {item['method']} {outcome} the baseline; "
                        f"the mean paired raw difference was {delta:+.6f}. This is not a statistical significance claim.")
    refs = [f"- {r['title']}: {r['url']} — {r['note']}" for r in plan["references"]]
    if not refs:
        refs = ["No literature sources were supplied. Literature review and novelty assessment remain pending."]
    body = (f"# {plan['title']}\n\n"
            "> LOCAL ENGINEERING DRAFT — generated by deterministic templates, not by a language model. "
            "Not a competition-ready manuscript.\n\n"
            f"## Research question\n\n{plan['question']}\n\n"
            f"## Hypothesis (pre-specified, not assumed true)\n\n{plan['hypothesis']}\n\n"
            f"## Protocol\n\nBaseline: `{plan['baseline']}`. Methods: {', '.join(plan['methods'])}. "
            f"Seeds: {plan['seeds']}. Metric: `{plan['primary_metric']}` ({plan['direction']}). "
            "The experiment script and its hash are archived under inputs/.\n\n"
            "## Results\n\n" + "\n".join(table) + "\n\n" + "\n\n".join(findings) + "\n\n"
            "## Evidence and reproducibility\n\nPer-seed results: results.csv. Raw artifacts and hashes: evidence.json. "
            "Each execution has command, stdout, stderr and timing logs. Use research-lab verify before trusting this draft.\n\n"
            "## Limitations\n\n" + "\n".join("- " + x for x in plan["limitations"]) + "\n\n"
            "## Supplied sources (not automatically verified)\n\n" + "\n".join(refs) + "\n")
    write_text(root / "paper_draft.md", body)
    tex_rows = "\n".join(f"{tex_escape(x['method'])} & {x['mean']:.6f} & {x['sample_stddev']:.6f} \\\\" for x in summary["methods"])
    latex = (r"\documentclass{article}" + "\n" + r"\usepackage[utf8]{inputenc}" + "\n"
             + r"\title{" + tex_escape(plan["title"]) + "}\n" + r"\author{Local engineering draft}" + "\n"
             + r"\begin{document}\maketitle" + "\n"
             + "DRAFT ONLY. Deterministic report; no LLM research or literature validation. "
             + "This uses the article class, not the official ICLR style.\n"
             + r"\section{Question}" + "\n" + tex_escape(plan["question"]) + "\n"
             + r"\section{Protocol}" + "\n" + tex_escape(f"Methods: {plan['methods']}; seeds: {plan['seeds']}; metric: {plan['primary_metric']}; direction: {plan['direction']}.") + "\n"
             + r"\section{Results}\begin{tabular}{lrr}Method & Mean & SD \\" + "\n" + tex_rows + "\n"
             + r"\end{tabular}" + "\n" + tex_escape(" ".join(findings)) + "\n"
             + r"\section{Limitations}" + "\n" + tex_escape(" ".join(plan["limitations"])) + "\n"
             + r"\end{document}" + "\n")
    write_text(root / "paper_draft.tex", latex)
    write_text(root / "resource_report.md", "# Resource report\n\n"
               + f"- Mode: offline-local; orchestrator LLM calls/tokens: 0/0.\n"
               + f"- Attempts: {resources['total_attempts']}; failed: {resources['failed_attempts']}.\n"
               + f"- Measured experiment wall time (including retries): {resources['experiment_wall_seconds_including_retries']:.3f} s.\n"
               + "- Monetary cost is unknown; experiment-specific model usage is in resource_report.json.\n")
    return summary
